# Generated by Django 2.0 on 2018-04-26 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180424_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '博客大类型',
                'verbose_name_plural': '博客大类型',
            },
        ),
        migrations.AlterModelOptions(
            name='blogtype',
            options={'verbose_name': '博客细类型', 'verbose_name_plural': '博客细类型'},
        ),
        migrations.AddField(
            model_name='blogtype',
            name='base_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BaseType'),
        ),
    ]
